[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.112.0"
uvicorn = { extras = ["standard"], version = "^0.30.5" }
pydantic = { extras = ["email"], version = "^2.8.2" }
pydantic-settings = "^2.4.0"
